export const DEFAULT_BULB_TEMP_VALUE = 0;
export const BULB_WARMEST_COLOR_IN_K = 2700;
export const BULB_COOLEST_COLOR_IN_K = 6500;
export const BULB_MIN_BRIGHTNESS = 0;
export const BULB_MAX_BRIGHTNESS = 100;

export const DEFAULT_AUTOREFRESH_INTERVAL_IN_MS = 5e3;
